"""fix circular import using deferred imports for BookingType and Booking

Revision ID: 67e8233488d6
Revises: d1f36dfda16c
Create Date: 2026-02-06 11:41:55.755689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e8233488d6'
down_revision: Union[str, Sequence[str], None] = 'd1f36dfda16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
