"""fix circular import using deferred imports for Booking and BookingType

Revision ID: d1f36dfda16c
Revises: 2598b047ea97
Create Date: 2026-02-06 11:37:43.977236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f36dfda16c'
down_revision: Union[str, Sequence[str], None] = '2598b047ea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
